// Tenant CRUD for the backend-admin dashboard — write-side of tenant/loader.ts.
// Only ever call these behind a SUPERADMIN guard; they operate across every
// hospital with no scoping, by design (that's the whole point of the
// internal admin surface — everything else in the app scopes to one
// hospital, this deliberately doesn't).

import { readFile, writeFile, readdir, mkdir } from "fs/promises";
import path from "path";
import type { TenantConfig, DocumentProfile, DocumentLibraryEntry, DocumentRequirement } from "./loader";
import { listCatalog, type CatalogEntry } from "../catalog";

const TENANTS_DIR = path.resolve(process.cwd(), "db", "tenants");

export async function listAllTenants(): Promise<TenantConfig[]> {
  try {
    const files = await readdir(TENANTS_DIR);
    const out: TenantConfig[] = [];
    for (const f of files.filter((x) => x.endsWith(".json"))) {
      try {
        out.push(JSON.parse(await readFile(path.join(TENANTS_DIR, f), "utf8")));
      } catch {
        // skip a corrupt file rather than fail the whole list
      }
    }
    return out.sort((a, b) => a.name.localeCompare(b.name));
  } catch {
    return [];
  }
}

async function readTenantFile(hospital_id: string): Promise<TenantConfig | null> {
  try {
    return JSON.parse(await readFile(path.join(TENANTS_DIR, `${hospital_id}.json`), "utf8"));
  } catch {
    return null;
  }
}

async function writeTenantFile(config: TenantConfig): Promise<void> {
  await mkdir(TENANTS_DIR, { recursive: true });
  await writeFile(path.join(TENANTS_DIR, `${config.hospital_id}.json`), JSON.stringify(config, null, 2));
}

function slugifyHospitalId(name: string): string {
  const base = name.trim().toUpperCase().replace(/[^A-Z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return `HOSP-${base.slice(0, 20)}-${Math.floor(1000 + Math.random() * 9000)}`;
}

export async function createTenant(input: {
  name: string;
  short_name: string;
  subdomain: string;
  state?: string;
  city: string;
  district: string;
  primary_color?: string;
  accent_color?: string;
  logo_initial?: string;
  tagline?: string;
}): Promise<TenantConfig> {
  const hospital_id = slugifyHospitalId(input.short_name || input.name);
  if (await readTenantFile(hospital_id)) {
    throw new Error(`Hospital id collision (${hospital_id}) — try again`);
  }
  const config: TenantConfig = {
    hospital_id,
    name: input.name,
    short_name: input.short_name,
    subdomain: input.subdomain.trim().toLowerCase(),
    logo_initial: input.logo_initial || input.name.trim()[0]?.toUpperCase() || "H",
    primary_color: input.primary_color || "#1a1a1a",
    accent_color: input.accent_color || "#2563eb",
    state: input.state,
    city: input.city,
    district: input.district,
    vocabulary: {},
    features: { whatsapp: true, nhcx_send: true },
    schemes_enabled: [],
    specialties_enabled: [],
    document_profiles: [],
    tagline: input.tagline || "",
  };
  await writeTenantFile(config);
  return config;
}

export async function updateTenant(hospital_id: string, patch: Partial<TenantConfig>): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  // hospital_id itself is never patchable — it's the filename/primary key.
  const { hospital_id: _ignore, ...rest } = patch;
  const updated: TenantConfig = { ...existing, ...rest };
  await writeTenantFile(updated);
  return updated;
}

// ---------- Document library + requirements (normalized replacement for
// document_profiles above) ----------
// document_profiles stays in the JSON file too, regenerated by
// flattenToDocumentProfiles() on every write below, purely so the Python
// classifier (tenant_config.py et al.), which only ever reads that flat
// shape, keeps working without any Python changes.

function flattenToDocumentProfiles(
  library: DocumentLibraryEntry[],
  requirements: DocumentRequirement[],
): DocumentProfile[] {
  const byDocType = new Map(library.map((l) => [l.doc_type, l]));
  const out: DocumentProfile[] = [];
  for (const r of requirements) {
    const entry = byDocType.get(r.doc_type);
    if (!entry) continue;
    out.push({
      doc_type: entry.doc_type,
      label: entry.label,
      specialty: r.specialty,
      stage: r.stage,
      for_treatments: r.for_treatments,
      schemes: r.schemes,
      alt_group: r.alt_group,
      anchors: entry.anchors,
      extraction_keys: entry.extraction_keys,
    });
  }
  return out;
}

async function persistDocumentModel(
  hospital_id: string,
  library: DocumentLibraryEntry[],
  requirements: DocumentRequirement[],
): Promise<TenantConfig> {
  return updateTenant(hospital_id, {
    document_library: library,
    document_requirements: requirements,
    document_profiles: flattenToDocumentProfiles(library, requirements),
  });
}

export async function addDocumentLibraryEntry(hospital_id: string, entry: DocumentLibraryEntry): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  const library = existing.document_library ?? [];
  if (library.some((l) => l.doc_type === entry.doc_type)) {
    throw new Error(`Document type ${entry.doc_type} already exists in the library`);
  }
  return persistDocumentModel(hospital_id, [...library, entry], existing.document_requirements ?? []);
}

export async function updateDocumentLibraryEntry(
  hospital_id: string,
  original_doc_type: string,
  entry: DocumentLibraryEntry,
): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  const library = existing.document_library ?? [];
  if (!library.some((l) => l.doc_type === original_doc_type)) {
    throw new Error(`Document type ${original_doc_type} not found in the library`);
  }
  if (entry.doc_type !== original_doc_type && library.some((l) => l.doc_type === entry.doc_type)) {
    throw new Error(`Document type ${entry.doc_type} already exists in the library`);
  }
  const newLibrary = library.map((l) => (l.doc_type === original_doc_type ? entry : l));
  // Renaming the slug must cascade into every requirement that points at it.
  const requirements = (existing.document_requirements ?? []).map((r) =>
    r.doc_type === original_doc_type ? { ...r, doc_type: entry.doc_type } : r,
  );
  return persistDocumentModel(hospital_id, newLibrary, requirements);
}

export async function removeDocumentLibraryEntry(hospital_id: string, doc_type: string): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  const library = (existing.document_library ?? []).filter((l) => l.doc_type !== doc_type);
  // Cascade — a requirement pointing at a deleted library entry is an
  // orphaned, meaningless row, same reasoning as department delete below.
  const requirements = (existing.document_requirements ?? []).filter((r) => r.doc_type !== doc_type);
  return persistDocumentModel(hospital_id, library, requirements);
}

function sameRequirementSlot(a: { doc_type: string; specialty: string; stage: string }, b: typeof a): boolean {
  return a.doc_type === b.doc_type && a.specialty === b.specialty && a.stage === b.stage;
}

// newEntry lets the caller define a never-seen-before doc_type and require
// it in the same request — keeps the admin UI a single form (label + slug +
// anchors + department + stage + schemes) instead of a separate "define the
// document" step. If doc_type already exists in the library, newEntry is
// ignored — reuse wins, so two departments never silently diverge on what
// "OT Notes" means.
export async function addDocumentRequirement(
  hospital_id: string,
  requirement: DocumentRequirement,
  newEntry?: { label: string; anchors: string[]; extraction_keys?: string[] },
): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  let library = existing.document_library ?? [];
  if (!library.some((l) => l.doc_type === requirement.doc_type)) {
    if (!newEntry) {
      throw new Error(`Document type ${requirement.doc_type} is not in the document library yet — provide a label and anchors to define it`);
    }
    // If this doc_type exists in the global catalog, mark the new entry
    // catalog_linked so future central catalog edits keep it in sync. A
    // brand-new doc_type not in the catalog stays a hospital-local override.
    const catalog = await listCatalog();
    const catalog_linked = catalog.some((c) => c.doc_type === requirement.doc_type);
    library = [...library, { doc_type: requirement.doc_type, label: newEntry.label, anchors: newEntry.anchors, extraction_keys: newEntry.extraction_keys, ...(catalog_linked ? { catalog_linked: true } : {}) }];
  }
  const requirements = existing.document_requirements ?? [];
  if (requirements.some((r) => sameRequirementSlot(r, requirement))) {
    throw new Error(`${requirement.doc_type} is already required for this department + stage`);
  }
  return persistDocumentModel(hospital_id, library, [...requirements, requirement]);
}

// libraryEdit updates the SHARED library entry (label/anchors) that every
// department using this doc_type sees — there's no per-department label
// override by design, so editing a requirement's label really does mean
// "rename this document everywhere it's used."
export async function updateDocumentRequirement(
  hospital_id: string,
  original: { doc_type: string; specialty: string; stage: string },
  requirement: DocumentRequirement,
  libraryEdit?: { label: string; anchors: string[]; extraction_keys?: string[] },
): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  let library = existing.document_library ?? [];
  if (!library.some((l) => l.doc_type === requirement.doc_type)) {
    throw new Error(`Document type ${requirement.doc_type} is not in the document library yet`);
  }
  if (libraryEdit) {
    // A hospital editing a doc's label/anchors locally DETACHES it from the
    // global catalog (catalog_linked:false) — from now on it's a per-hospital
    // override that central catalog edits won't overwrite.
    library = library.map((l) =>
      l.doc_type === requirement.doc_type
        ? { ...l, label: libraryEdit.label, anchors: libraryEdit.anchors, extraction_keys: libraryEdit.extraction_keys, catalog_linked: false }
        : l,
    );
  }
  const requirements = existing.document_requirements ?? [];
  if (!requirements.some((r) => sameRequirementSlot(r, original))) {
    throw new Error("Requirement not found");
  }
  if (
    !sameRequirementSlot(original, requirement) &&
    requirements.some((r) => sameRequirementSlot(r, requirement))
  ) {
    throw new Error(`${requirement.doc_type} is already required for this department + stage`);
  }
  const newRequirements = requirements.map((r) => (sameRequirementSlot(r, original) ? requirement : r));
  return persistDocumentModel(hospital_id, library, newRequirements);
}

export async function removeDocumentRequirement(
  hospital_id: string,
  slot: { doc_type: string; specialty: string; stage: string },
): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  const library = existing.document_library ?? [];
  const requirements = (existing.document_requirements ?? []).filter((r) => !sameRequirementSlot(r, slot));
  return persistDocumentModel(hospital_id, library, requirements);
}

// ---------- Departments (specialties_enabled) ----------
// A "department" is just a slug string in specialties_enabled — no separate
// label storage, the slug IS the display text (kept lowercase_with_underscores
// for consistency with how Python/TS read it elsewhere). Rename/delete cascade
// into document_profiles so nothing is left pointing at a department that no
// longer exists.

function slugifyDepartment(name: string): string {
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

export async function addSpecialty(hospital_id: string, name: string): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  const slug = slugifyDepartment(name);
  if (!slug) throw new Error("Department name required");
  const specialties = Array.from(new Set([...(existing.specialties_enabled ?? []), slug]));
  return updateTenant(hospital_id, { specialties_enabled: specialties });
}

export async function renameSpecialty(hospital_id: string, oldSlug: string, newName: string): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  const newSlug = slugifyDepartment(newName);
  if (!newSlug) throw new Error("New department name required");
  const specialties = Array.from(
    new Set((existing.specialties_enabled ?? []).map((s) => (s === oldSlug ? newSlug : s)))
  );
  const requirements = (existing.document_requirements ?? []).map((r) =>
    r.specialty === oldSlug ? { ...r, specialty: newSlug } : r
  );
  const library = existing.document_library ?? [];
  return updateTenant(hospital_id, {
    specialties_enabled: specialties,
    document_requirements: requirements,
    document_profiles: flattenToDocumentProfiles(library, requirements),
  });
}

export async function deleteSpecialty(hospital_id: string, slug: string): Promise<TenantConfig> {
  const existing = await readTenantFile(hospital_id);
  if (!existing) throw new Error(`Hospital ${hospital_id} not found`);
  const specialties = (existing.specialties_enabled ?? []).filter((s) => s !== slug);
  // Cascade — an orphaned document requirement pointing at a deleted
  // department is a broken/confusing state, not a useful one. The library
  // entry itself survives (it may still be used by other departments).
  const requirements = (existing.document_requirements ?? []).filter((r) => r.specialty !== slug);
  const library = existing.document_library ?? [];
  return updateTenant(hospital_id, {
    specialties_enabled: specialties,
    document_requirements: requirements,
    document_profiles: flattenToDocumentProfiles(library, requirements),
  });
}

// ---------- Global catalog → tenant propagation ----------
// Called by the catalog API after a catalog entry is edited or deleted. Walks
// every hospital and updates the ones whose document_library holds a
// catalog_linked copy of the changed doc_type — that's how a central edit
// "live-propagates" to all hospitals, while per-hospital overrides
// (catalog_linked:false) are left untouched. Returns the number of hospitals
// actually changed, for the API to report back.

async function forEachTenant(fn: (t: TenantConfig) => TenantConfig | null): Promise<number> {
  let files: string[] = [];
  try {
    files = (await readdir(TENANTS_DIR)).filter((x) => x.endsWith(".json"));
  } catch {
    return 0;
  }
  let changed = 0;
  for (const f of files) {
    let t: TenantConfig;
    try {
      t = JSON.parse(await readFile(path.join(TENANTS_DIR, f), "utf8"));
    } catch {
      continue;
    }
    const next = fn(t);
    if (next) {
      await writeTenantFile(next);
      changed++;
    }
  }
  return changed;
}

// A catalog entry was created/renamed/edited. Re-sync every catalog_linked
// copy: update label/anchors/extraction_keys, and if the slug changed, rename
// the doc_type in both library and requirements so the join stays intact.
export async function propagateCatalogUpsert(
  originalDocType: string,
  entry: CatalogEntry,
): Promise<number> {
  return forEachTenant((t) => {
    const library = t.document_library ?? [];
    const idx = library.findIndex((l) => l.doc_type === originalDocType && l.catalog_linked);
    if (idx < 0) return null;
    const newLibrary = library.map((l) =>
      l.doc_type === originalDocType && l.catalog_linked
        ? { ...l, doc_type: entry.doc_type, label: entry.label, anchors: entry.anchors, extraction_keys: entry.extraction_keys, catalog_linked: true }
        : l,
    );
    const requirements = (t.document_requirements ?? []).map((r) =>
      r.doc_type === originalDocType ? { ...r, doc_type: entry.doc_type } : r,
    );
    return {
      ...t,
      document_library: newLibrary,
      document_requirements: requirements,
      document_profiles: flattenToDocumentProfiles(newLibrary, requirements),
    };
  });
}

// A catalog entry was deleted. Don't delete the hospitals' copies (that would
// silently drop live requirements) — just DETACH them (catalog_linked:false)
// so they keep working as hospital-local definitions with their current
// label/anchors, and simply stop syncing.
export async function propagateCatalogDelete(docType: string): Promise<number> {
  return forEachTenant((t) => {
    const library = t.document_library ?? [];
    if (!library.some((l) => l.doc_type === docType && l.catalog_linked)) return null;
    const newLibrary = library.map((l) =>
      l.doc_type === docType && l.catalog_linked ? { ...l, catalog_linked: false } : l,
    );
    const requirements = t.document_requirements ?? [];
    return {
      ...t,
      document_library: newLibrary,
      document_requirements: requirements,
      document_profiles: flattenToDocumentProfiles(newLibrary, requirements),
    };
  });
}
