"use client";

import { useEffect, useMemo, useRef, useState, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import AppShell from "@/components/AppShell";
import { matchPatient } from "@/lib/patientMatch";
import { SPECIALTY_META, ALL_SCHEMES } from "@/lib/types";
import type { Specialty, Treatment } from "@/lib/types";
import { useRoleGate } from "@/lib/useRoleGate";

// All Indian states + union territories, for the State field's suggestion list.
const INDIA_STATES_UTS = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa",
  "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala",
  "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland",
  "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal",
  "Andaman and Nicobar Islands", "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Jammu and Kashmir",
  "Ladakh", "Lakshadweep", "Puducherry",
];

type HandoverEntry = {
  id: string;
  pushed_at: string;
  scheme: string;
  card: string;
  aadhaar_last4?: string;
  beneficiary: { name: string; age: number; gender: "M" | "F"; state: string; district: string };
  wallet: { available_inr: number; cap_inr: number };
  status: "pending" | "consumed";
};

function OPDRegistrationContent() {
  useRoleGate(["ADMIN"], "/patients");
  const router = useRouter();
  const searchParams = useSearchParams();

  // Edit mode: PatientHeader's ✎ edit icon links here with
  // ?edit=1&patient_id=&case_id=&<current field values>. Core identity/
  // registration fields (MRN, name, scheme, treatment type, ...) live here
  // and only here — the patient-detail page and the NHCX review screen both
  // intentionally route corrections back to this one screen rather than
  // letting them be edited in three different places with three different
  // validation rules.
  const isEdit = searchParams.get("edit") === "1";
  const editPatientId = searchParams.get("patient_id") || "";
  const editCaseId = searchParams.get("case_id") || "";
  const [editSaving, setEditSaving] = useState(false);
  const [editError, setEditError] = useState<string | null>(null);

  const [phase, setPhase] = useState<"register" | "review">("register");
  const [hasHis, setHasHis] = useState<"yes" | "no" | null>(null);

  // Patient
  const [name, setName] = useState("");
  const [mrn, setMrn] = useState("");
  const [age, setAge] = useState("");
  const [gender, setGender] = useState("M");
  const [state, setStateF] = useState("");
  const [scheme, setScheme] = useState("");
  const [wallet, setWallet] = useState<{ available: number; cap: number } | null>(null);

  // Consult
  const [specialty, setSpecialty] = useState<Specialty>("oncology");
  const [treatment, setTreatment] = useState<Treatment>("chemo");
  const [reasonForVisit, setReasonForVisit] = useState("");
  const [doctor, setDoctor] = useState("");
  const [saved, setSaved] = useState<{
    caseCode: string; mrn: string; mrnAutoGenerated: boolean; patientId: string;
    mrnConflict: boolean; providedMrn?: string;
  } | null>(null);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  // Prefill from the query params PatientHeader's edit link supplies —
  // this only runs once (edit mode never re-triggers a re-prefill mid-edit).
  useEffect(() => {
    if (!isEdit) return;
    const g = searchParams.get("name"); if (g) setName(g);
    const m = searchParams.get("mrn"); if (m) setMrn(m);
    const a = searchParams.get("age"); if (a) setAge(a);
    const gd = searchParams.get("gender"); if (gd) setGender(gd);
    const st = searchParams.get("state"); if (st) setStateF(st);
    const sc = searchParams.get("scheme"); if (sc) setScheme(sc);
    const sp = searchParams.get("specialty") as Specialty | null;
    const resolvedSpecialty = sp && SPECIALTY_META[sp] ? sp : specialty;
    if (sp && SPECIALTY_META[sp]) setSpecialty(sp);
    // A stale/invalid treatment value (e.g. the "pending" sentinel written
    // at auto-create, before any human picked a real treatment) must not be
    // written into state — the <select> below silently falls back to
    // displaying its first option when the controlled value matches no
    // <option>, which desyncs the visible dropdown from `treatment` and
    // makes Save silently resubmit the stale value. Skipping keeps the two
    // in sync (state already defaults to the same first option).
    const tr = searchParams.get("treatment") as Treatment | null;
    if (tr && SPECIALTY_META[resolvedSpecialty].treatments.includes(tr)) setTreatment(tr);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const saveEdit = async () => {
    if (!editPatientId || !editCaseId) return;
    setEditSaving(true);
    setEditError(null);
    try {
      const patientRes = await fetch(`/api/patients/${encodeURIComponent(editPatientId)}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, mrn, age, gender }),
      }).then((r) => r.json());
      if (!patientRes.ok) { setEditError(patientRes.error ?? "Couldn't save patient details"); return; }

      const caseRes = await fetch(`/api/cases/${encodeURIComponent(editCaseId)}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ scheme, specialty, treatment_type: treatment }),
      }).then((r) => r.json());
      if (!caseRes.ok) { setEditError(caseRes.error ?? "Couldn't save case details"); return; }

      router.push(`/patient/${encodeURIComponent(editPatientId)}?case=${encodeURIComponent(editCaseId)}`);
    } catch (e: any) {
      setEditError(e?.message ?? "Couldn't save changes");
    } finally {
      setEditSaving(false);
    }
  };

  // Handover queue polling
  const [queue, setQueue] = useState<HandoverEntry[]>([]);
  useEffect(() => {
    if (isEdit) return; // editing an existing patient — the handover queue is for new registrations only
    let stopped = false;
    const fetchQueue = async () => {
      try {
        const r = await fetch("/api/handover", { cache: "no-store" });
        const j = await r.json();
        if (!stopped && j.ok) setQueue(j.queue);
      } catch {}
    };
    fetchQueue();
    const id = setInterval(fetchQueue, 4000);
    return () => { stopped = true; clearInterval(id); };
  }, []);

  const loadFromHandover = async (h: HandoverEntry) => {
    setName(h.beneficiary.name);
    setAge(String(h.beneficiary.age));
    setGender(h.beneficiary.gender);
    setStateF(h.beneficiary.state);
    setScheme(h.scheme);
    setWallet({ available: h.wallet.available_inr, cap: h.wallet.cap_inr });
    setMrn(""); // hospital MRN assigned at OPD, not pulled from scheme
    await fetch(`/api/handover?id=${encodeURIComponent(h.id)}`, { method: "DELETE" });
    setQueue((q) => q.filter((x) => x.id !== h.id));
  };

  const matchResult = useMemo(() => matchPatient({ name, mrn, age, gender }), [name, mrn, age, gender]);
  const matched = matchResult.match;

  const review = () => setPhase("review");
  const save   = async () => {
    setSaving(true);
    setSaveError(null);
    try {
      const res = await fetch("/api/opd/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name, mrn, age, gender, state, scheme,
          specialty, treatment, doctor, reasonForVisit,
        }),
      });
      const json = await res.json();
      if (!json.ok) {
        setSaveError(json.error ?? "Could not create case");
        return;
      }
      setSaved({
        caseCode: json.case_id, mrn: json.mrn, mrnAutoGenerated: json.mrn_auto_generated,
        patientId: json.patient_id, mrnConflict: json.mrn_conflict, providedMrn: json.provided_mrn,
      });
      if (json.mrn_auto_generated) setMrn(json.mrn);
    } catch (e: any) {
      setSaveError(e?.message ?? "Could not create case");
    } finally {
      setSaving(false);
    }
  };

  const canReview = (!!matched || !!name || !!mrn) && !!reasonForVisit;

  return (
    <AppShell>
      <div className="space-y-6 max-w-5xl">
        <div className="flex items-end justify-between flex-wrap gap-3">
          <div>
            <h1 className="text-xl font-bold text-ink-100">
              {isEdit ? "Edit Patient & Case Details" : "OPD Registration · Doctor Consult"}
            </h1>
            <p className="text-sm text-ink-300 mt-1">
              {isEdit
                ? "Correct name, MRN, scheme, or treatment type. Saving takes you back to this patient's page."
                : "Register the patient and capture the reason for visit and treatment plan in one go — the doctor records the diagnosis separately during consult. Output: a case the rest of MedLynq tracks."}
            </p>
          </div>
          {!isEdit && <PhasePill phase={phase} />}
        </div>

        {/* Handover notification banner */}
        {!isEdit && queue.length > 0 && phase === "register" && (
          <div className="bg-accent-soft border border-accent/40 rounded-lg p-3 space-y-2">
            <div className="flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-accent text-white grid place-items-center text-xs">📨</span>
              <div>
                <div className="text-sm font-bold text-ink-100">
                  {queue.length} verified patient{queue.length === 1 ? "" : "s"} pending registration
                </div>
                <div className="text-[10px] text-ink-300">Backend Panel verified the card · click to load into the form below</div>
              </div>
            </div>
            <ul className="space-y-1">
              {queue.map((h) => (
                <li key={h.id} className="bg-bone-0 border border-bone-300 rounded p-2 text-xs flex items-center justify-between gap-3">
                  <div className="flex-1 min-w-0">
                    <div className="font-bold text-ink-100">{h.beneficiary.name}</div>
                    <div className="text-[10px] text-ink-300">
                      {h.scheme} · {h.beneficiary.gender === "M" ? "M" : "F"} · {h.beneficiary.age}y · {h.beneficiary.district}, {h.beneficiary.state} · wallet ₹{h.wallet.available_inr.toLocaleString("en-IN")}
                    </div>
                  </div>
                  <button onClick={() => loadFromHandover(h)} className="text-xs font-semibold px-3 py-1 bg-accent text-white rounded hover:opacity-90">
                    Load into form →
                  </button>
                </li>
              ))}
            </ul>
          </div>
        )}

        {phase === "register" && (
          <div className="bg-bone-0 border border-bone-300 rounded-lg p-5 space-y-4">
            <h2 className="text-sm font-bold text-ink-100">Patient + consult</h2>

            <div className="grid md:grid-cols-2 gap-3">
              <Input label="Name" value={name} onChange={setName} placeholder="Full name" />
              <Input label="Assign MRN / Hospital ID" value={mrn} onChange={setMrn} placeholder="e.g. MRN12345" mono />
              <Input
                label="Age" value={age}
                onChange={(v) => setAge(v.replace(/\D/g, "").slice(0, 3))}
                placeholder="42" inputMode="numeric" pattern="[0-9]*" maxLength={3}
              />
              <div>
                <Label>Gender</Label>
                <select value={gender} onChange={(e) => setGender(e.target.value)} className={selectCls}>
                  <option value="M">Male</option><option value="F">Female</option>
                </select>
              </div>
              <StateAutocomplete value={state} onChange={setStateF} />
              <SchemeAutocomplete value={scheme} onChange={setScheme} />
            </div>

            {wallet && (
              <div className="bg-good-soft border border-good/40 rounded p-2 text-xs">
                <span className="font-bold text-good">✓ Wallet</span> available <strong>₹{wallet.available.toLocaleString("en-IN")}</strong> of ₹{wallet.cap.toLocaleString("en-IN")} cap
              </div>
            )}

            {!isEdit && (
              <div className={`rounded p-3 border text-sm ${
                matched ? "bg-good-soft border-good/40" : (name || mrn) ? "bg-warn-soft border-warn/40" : "bg-bone-100 border-bone-300 text-ink-300 italic"
              }`}>
                {matched ? (
                  <>
                    <div className="font-bold text-good">✓ Matched existing patient</div>
                    <div className="text-ink-100">{matched.name} · MRN {matched.mrn} · age {matched.age}</div>
                  </>
                ) : (name || mrn) ? (
                  <div className="font-bold text-warn">No existing patient — will register as new</div>
                ) : "Type to search or load from the handover banner above."}
              </div>
            )}

            <div className="grid md:grid-cols-3 gap-3">
              <div>
                <Label>Specialty</Label>
                <select value={specialty} onChange={(e) => {
                  const sp = e.target.value as Specialty;
                  setSpecialty(sp);
                  setTreatment(SPECIALTY_META[sp].treatments[0]);
                }} className={selectCls}>
                  {(Object.keys(SPECIALTY_META) as Specialty[]).map((s) => (
                    <option key={s} value={s}>{SPECIALTY_META[s].label}</option>
                  ))}
                </select>
              </div>
              <div>
                <Label>Treatment plan</Label>
                <select value={treatment} onChange={(e) => setTreatment(e.target.value as Treatment)} className={selectCls}>
                  {SPECIALTY_META[specialty].treatments.map((t) => <option key={t} value={t}>{t}</option>)}
                </select>
              </div>
              {!isEdit && <Input label="Consulting doctor" value={doctor} onChange={setDoctor} placeholder="Dr. ..." />}
            </div>

            {!isEdit && (
              <div>
                <Label>Reason for Visit</Label>
                <textarea value={reasonForVisit} onChange={(e) => setReasonForVisit(e.target.value)}
                  placeholder="E.g. Lump in left breast, ongoing 3 months. (The doctor records the diagnosis separately during consult.)"
                  rows={2} className={textAreaCls} />
              </div>
            )}

            {isEdit ? (
              <div className="space-y-2">
                {editError && (
                  <div className="text-xs text-bad bg-bad-soft border border-bad/40 rounded px-3 py-2">{editError}</div>
                )}
                <div className="flex justify-end gap-2">
                  <a href={`/patient/${encodeURIComponent(editPatientId)}?case=${encodeURIComponent(editCaseId)}`}
                    className="text-xs px-3 py-1.5 border border-bone-300 rounded hover:bg-bone-200">
                    ← Cancel
                  </a>
                  <button
                    onClick={saveEdit}
                    disabled={editSaving || !name.trim() || !mrn.trim()}
                    className="text-xs font-semibold px-4 py-2 bg-accent text-white rounded hover:opacity-90 disabled:opacity-40"
                  >{editSaving ? "Saving…" : "💾 Save changes"}</button>
                </div>
              </div>
            ) : (
              <div className="flex justify-end">
                <button
                  onClick={review}
                  disabled={!canReview}
                  className="text-xs font-semibold px-4 py-2 bg-accent text-white rounded hover:opacity-90 disabled:opacity-40"
                >Review & create case →</button>
              </div>
            )}
          </div>
        )}

        {!isEdit && phase === "review" && (
          <div className="bg-bone-0 border border-bone-300 rounded-lg p-5 space-y-4">
            <h2 className="text-sm font-bold text-ink-100">Review & create case</h2>

            {/* HIS decision */}
            {!saved && (
              <div className="bg-bone-100 border border-bone-300 rounded p-3 space-y-2">
                <div className="text-xs font-bold text-ink-100">Does this hospital use an HIS today?</div>
                <div className="flex gap-2 flex-wrap">
                  <button onClick={() => setHasHis("yes")} className={`text-xs font-semibold px-3 py-1.5 rounded border ${
                    hasHis === "yes" ? "bg-accent text-white border-accent" : "bg-bone-0 text-ink-200 border-bone-300"
                  }`}>Yes · I&apos;ll copy into HIS manually</button>
                  <button onClick={() => setHasHis("no")} className={`text-xs font-semibold px-3 py-1.5 rounded border ${
                    hasHis === "no" ? "bg-accent text-white border-accent" : "bg-bone-0 text-ink-200 border-bone-300"
                  }`}>No · MedLynq is my system of record</button>
                </div>
                <div className="text-[10px] text-ink-300 italic">
                  When the hospital HIS API is granted, the &quot;Connect to HIS&quot; option auto-pushes this patient into the HIS portal.
                </div>
              </div>
            )}

            <div className="grid md:grid-cols-2 gap-3 text-sm">
              <Cell label="Patient" value={matched ? matched.name : name} />
              <Cell label="MRN"     value={matched ? matched.mrn  : mrn || "—"} />
              <Cell label="Age · Gender" value={`${age || "—"} · ${gender === "M" ? "Male" : "Female"}`} />
              <Cell label="Scheme" value={scheme || "—"} />
              <Cell label="Specialty + treatment" value={`${SPECIALTY_META[specialty].label} · ${treatment}`} />
              <Cell label="Doctor" value={doctor || "—"} />
              <Cell label="Reason for Visit" value={reasonForVisit} multi />
              {wallet && <Cell label="Wallet" value={`₹${wallet.available.toLocaleString("en-IN")} of ₹${wallet.cap.toLocaleString("en-IN")}`} multi />}
            </div>

            {!saved ? (
              <div className="space-y-2">
                {saveError && (
                  <div className="text-xs text-bad bg-bad-soft border border-bad/40 rounded px-3 py-2">{saveError}</div>
                )}
                <div className="flex justify-between">
                  <button onClick={() => setPhase("register")} className="text-xs px-3 py-1.5 border border-bone-300 rounded hover:bg-bone-200">← Back</button>
                  <button onClick={save} disabled={!hasHis || saving}
                    className="text-xs font-semibold px-4 py-2 bg-accent text-white rounded hover:opacity-90 disabled:opacity-40">
                    {saving ? "Creating…" : "✓ Create case"}
                  </button>
                </div>
              </div>
            ) : (
              <div className={`rounded p-3 border space-y-3 ${hasHis === "yes" ? "bg-warn-soft border-warn/40" : "bg-good-soft border-good/40"}`}>
                <div className={`font-bold ${hasHis === "yes" ? "text-warn" : "text-good"}`}>
                  ✓ Case {saved.caseCode} created · MRN {saved.mrn}
                  {saved.mrnAutoGenerated && <span className="ml-2 text-[10px] font-semibold uppercase text-accent">MedLynq-assigned (no HIS)</span>}
                </div>
                {saved.mrnConflict && (
                  <div className="text-xs bg-warn-soft border border-warn/40 rounded px-3 py-2 text-ink-100">
                    <strong>Note:</strong> this matched an existing patient on file under MRN <span className="font-mono">{saved.mrn}</span>.
                    The MRN you entered (<span className="font-mono">{saved.providedMrn}</span>) doesn&apos;t match — no duplicate patient was created,
                    but please reconcile which MRN is correct for this patient manually.
                  </div>
                )}

                {hasHis === "yes" ? (
                  <div className="space-y-2 text-sm">
                    <div className="text-ink-200">
                      <strong>Hospital HIS detected.</strong> Copy these fields into your HIS portal manually,
                      then come back to confirm.
                    </div>
                    <div className="bg-bone-0 border border-bone-300 rounded p-3 grid md:grid-cols-2 gap-2 text-xs">
                      <CopyRow label="Name" value={name} />
                      <CopyRow label="MRN" value={mrn} />
                      <CopyRow label="Age" value={age} />
                      <CopyRow label="Gender" value={gender} />
                      <CopyRow label="State" value={state} />
                      <CopyRow label="Scheme" value={scheme} />
                      <CopyRow label="Reason for Visit" value={reasonForVisit} />
                      <CopyRow label="Doctor" value={doctor} />
                    </div>
                    <div className="flex items-center gap-2">
                      <button disabled className="text-xs font-semibold px-3 py-1.5 bg-ink-300 text-white rounded opacity-60">
                        🔌 Connect to HIS API (soon)
                      </button>
                      <a href="/patients" className="text-xs px-3 py-1.5 border border-bone-300 rounded hover:bg-bone-200 bg-bone-0">
                        Add to MedLynq Patient List
                      </a>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-2 text-sm">
                    <div className="text-ink-200">
                      MedLynq is the system of record. The patient is in the Patient List and ready to receive documents.
                    </div>
                    <div className="flex items-center gap-2">
                      <a
                        href={`/intake?mrn=${encodeURIComponent(saved.mrn)}&name=${encodeURIComponent(name)}&patient_id=${encodeURIComponent(saved.patientId)}`}
                        className="text-xs font-semibold px-3 py-1.5 bg-accent text-white rounded"
                      >
                        Upload documents →
                      </a>
                      <a href="/patients" className="text-xs px-3 py-1.5 border border-bone-300 rounded hover:bg-bone-200 bg-bone-0">
                        Open patient list
                      </a>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </AppShell>
  );
}

export default function OPDRegistrationPage() {
  return (
    <Suspense fallback={
      <AppShell>
        <div className="p-4 text-sm text-ink-300">Loading OPD registration...</div>
      </AppShell>
    }>
      <OPDRegistrationContent />
    </Suspense>
  );
}

const selectCls   = "w-full text-sm px-3 py-2 bg-bone-0 border border-bone-300 rounded focus:outline-none focus:border-accent";
const textAreaCls = "w-full text-sm px-3 py-2 bg-bone-0 border border-bone-300 rounded focus:outline-none focus:border-accent resize-none";

function Label({ children }: { children: React.ReactNode }) {
  return <div className="text-[10px] uppercase tracking-wide text-ink-300 font-semibold mb-1">{children}</div>;
}

// Custom-styled autocomplete — a native <datalist> browser dropdown can't be
// positioned/styled and was appearing offset from the actual input on some
// screens. This renders the suggestion list ourselves, anchored directly
// under the input via relative/absolute positioning.
function StateAutocomplete({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function onClickOutside(e: MouseEvent) {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", onClickOutside);
    return () => document.removeEventListener("mousedown", onClickOutside);
  }, []);

  const matches = value.trim()
    ? INDIA_STATES_UTS.filter((s) => s.toLowerCase().includes(value.trim().toLowerCase()))
    : INDIA_STATES_UTS;

  return (
    <div className="relative" ref={wrapRef}>
      <Label>State</Label>
      <input
        type="text" value={value}
        onChange={(e) => { onChange(e.target.value); setOpen(true); }}
        onFocus={() => setOpen(true)}
        placeholder="Karnataka" className={selectCls} autoComplete="off"
      />
      {open && matches.length > 0 && (
        <ul className="absolute z-20 mt-1 w-full max-h-48 overflow-auto bg-bone-0 border border-bone-300 rounded shadow-lg text-sm">
          {matches.map((s) => (
            <li
              key={s}
              onMouseDown={() => { onChange(s); setOpen(false); }}
              className="px-3 py-1.5 hover:bg-accent-soft hover:text-accent cursor-pointer"
            >
              {s}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
function SchemeAutocomplete({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function onClickOutside(e: MouseEvent) {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", onClickOutside);
    return () => document.removeEventListener("mousedown", onClickOutside);
  }, []);

  const matches = value.trim()
    ? ALL_SCHEMES.filter((s) => s.toLowerCase().includes(value.trim().toLowerCase()))
    : ALL_SCHEMES;

  return (
    <div className="relative" ref={wrapRef}>
      <Label>Scheme</Label>
      <input
        type="text" value={value}
        onChange={(e) => { onChange(e.target.value); setOpen(true); }}
        onFocus={() => setOpen(true)}
        placeholder="PMJAY" className={selectCls} autoComplete="off"
      />
      {open && matches.length > 0 && (
        <ul className="absolute z-20 mt-1 w-full max-h-48 overflow-auto bg-bone-0 border border-bone-300 rounded shadow-lg text-sm">
          {matches.map((s) => (
            <li
              key={s}
              onMouseDown={() => { onChange(s); setOpen(false); }}
              className="px-3 py-1.5 hover:bg-accent-soft hover:text-accent cursor-pointer"
            >
              {s}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
function Input({ label, value, onChange, placeholder, mono, inputMode, pattern, maxLength }: {
  label: string; value: string; onChange: (v: string) => void; placeholder?: string; mono?: boolean;
  inputMode?: React.HTMLAttributes<HTMLInputElement>["inputMode"]; pattern?: string; maxLength?: number;
}) {
  return (
    <div>
      <Label>{label}</Label>
      <input
        type="text" value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder}
        inputMode={inputMode} pattern={pattern} maxLength={maxLength}
        className={`${selectCls} ${mono ? "font-mono" : ""}`}
      />
    </div>
  );
}
function Cell({ label, value, multi }: { label: string; value: string; multi?: boolean }) {
  return (
    <div className={multi ? "md:col-span-2" : ""}>
      <Label>{label}</Label>
      <div className="text-ink-100">{value || "—"}</div>
    </div>
  );
}
function CopyRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-2 py-1 border-b border-bone-200 last:border-0">
      <div>
        <div className="text-[9px] uppercase tracking-wide text-ink-300 font-semibold">{label}</div>
        <div className="text-ink-100 font-mono">{value || "—"}</div>
      </div>
      <button
        onClick={() => navigator.clipboard.writeText(value || "")}
        className="text-[10px] px-2 py-0.5 border border-bone-300 rounded hover:bg-bone-200 shrink-0"
      >Copy</button>
    </div>
  );
}
function PhasePill({ phase }: { phase: "register" | "review" }) {
  const stages: Array<{ key: typeof phase; label: string }> = [
    { key: "register", label: "Register + Consult" },
    { key: "review", label: "Review" },
  ];
  return (
    <div className="flex items-center gap-1">
      {stages.map((s, i) => (
        <div key={s.key} className="flex items-center gap-1">
          <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded-full border ${
            s.key === phase ? "bg-accent text-white border-accent" : "bg-bone-0 text-ink-300 border-bone-300"
          }`}>{i + 1}. {s.label}</span>
          {i < stages.length - 1 && <span className="text-ink-300">→</span>}
        </div>
      ))}
    </div>
  );
}
